### ISSUE TITLE
CefSharp cannot be installed

### ISSUE THREAD

**Issue by melorin83** [gro-ove/actools#101]
![2024-02-12 09_50_01-Content Manager](https://github.com/gro-ove/actools/assets/92246522/bbf235a9-3e61-4fb0-a4b5-836bf988cc45)
09:37:24.273: ⚠ [I] Cannot get plugins/get/CefSharp-114.2.120-x86: InternalServerError, System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
	   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
	   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
	   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at AcManager.Internal.InternalUtils.HPRqfhqmvQTAdfDspqhOaGGRjPpR.MoveNext()

**Comment by fafafagdfg** [comment]
can you open this question?

**Comment by doggbmx** [comment]
open this question plz
