### ISSUE TITLE
Linux crashes after choosing "Add a shortcut to start menu" on the first boot setup screen

### ISSUE THREAD

**Issue by realairacobra** [gro-ove/actools#121]
Pretty self explanatory, i was setting it all up, worked fine until i clicked add and it all stopped working, tried deleting the shortcut, all the data from acmanager and nothing worked, it just shows a black screen for a second and closes when i open it up

**Comment by sihawido** [comment]
If you have installed AC in your home directory then deleting `Content Manager.lnk` in `~/.local/share/Steam/steamapps/compatdata/244210/pfx/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Content Manager.lnk` Should fix it.

Or just run
```
rm "~/.local/share/Steam/steamapps/compatdata/244210/pfx/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Content Manager.lnk"
```

**Comment by JesseAye** [comment]
On Arch Linux with GE-Proton9-2, I hit this same bug from three different entry points, all resolved by removing/avoiding the .lnk file:

1. Clicking "Create (recommended)" for the Start Menu shortcut on the first-run setup screen crashes CM immediately, same as the original report in this issue.
2. Once a Content Manager.lnk exists (however it got there), CM crashes on every subsequent launch until the .lnk is deleted or renamed.
3. Separately, even with a working install, opening Settings > Content Manager > General throws instead of crashing the whole app, which is slightly better, but makes General inaccessible:
```
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'AcManager.Pages.Settings.SettingsGeneral' that matches the specified binding constraints threw an exception. ---> System.NotImplementedException: The method or operation is not implemented.
   at FirstFloor.ModernUI.Windows.ShellLink.IPropertyStore.GetValue(PropertyKey& key, PropVariant pv)
   at FirstFloor.ModernUI.Windows.ShellLink.get_AppUserModelId()
   at FirstFloor.ModernUI.Windows.AppShortcut.HasShortcut()
   at AcManager.Pages.Settings.SettingsGeneral.ViewModel..ctor()
   at AcManager.Pages.Settings.SettingsGeneral..ctor()
```
All three point to the same root cause: `AppShortcut.HasShortcut()` / the shortcut-creation path reads or writes the `.lnk` file's `IPropertyStore`, querying or setting the AppUserModelID property. Wine's shell32 doesn't fully implement that COM interface for shortcut files, so instead of a normal HRESULT it throws `NotImplementedException`, which isn't caught anywhere in the call chain, taking down whichever page or the whole app triggered it.

Workaround that resolves all three cases: don't create the shortcut (skip it), and manually delete it if one already exists:
```
rm "~/.local/share/Steam/steamapps/compatdata/244210/pfx/drive_c/users/steamuser/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Content Manager.lnk"
```
Since this is a Wine/Proton limitation rather than something Linux users can fix on their end, it'd help a lot if the shortcut-related calls (`HasShortcut()`, the creation path, and anything else touching `IPropertyStore` on the `.lnk`) caught exceptions and degraded gracefully instead of crashing the caller. Shortcut/notification support isn't essential functionality, it shouldn't be able to take down setup or settings.
