### ISSUE TITLE
Content Manager cannot download anything

### ISSUE THREAD

**Issue by jonaskoen** [gro-ove/actools#36]
My Content Manager is not able to download CSP and any configs (when I start a session it loads very long at the point "loading data for custom shaders patch") but on the other hand the release notes are loading. 
The error:
![errorContentManager](https://user-images.githubusercontent.com/56636880/115834291-59099200-a415-11eb-96b7-1f643099cea8.PNG)
<details>
<summary>Content Manager Log file</summary>

> 09:00:12.704: Initialized
09:00:12.720: → [App:104] CreateAndRun(): App version: 0.8.2245.37760 (x86, Windows 10)
09:00:12.746: → [LocaleHelper:40] InitializeAsync(): Language ID: en
09:00:12.746: → [LocaleHelper:44] InitializeAsync(): Supported officially
09:00:13.376: → [WebBrowserHelper:27] SetBrowserFeatureControlKey(): SetBrowserFeatureControlKey('Content Manager.exe', '11999')
09:00:13.376: → [WebBrowserHelper:27] SetBrowserFeatureControlKey(): SetBrowserFeatureControlKey('Content Manager.exe', '1')
09:00:13.469: → [AppAppearanceManager:173] InnerInitialize(): Accent color: #FFA20025
09:00:13.627: ⚠ [ModsWebBrowser:670] AddDefaultSources(): File Website.json is missing
09:00:13.640: … [ModsWebBrowser:223] Favicon(): http://assettocorsamods.net/favicon.ico
09:00:13.640: … [ModsWebBrowser:223] Favicon(): http://assettocorsamods.net/styles/casual/xenforo/logo_ACM.png
09:00:13.652: ⚠ [DataUpdater:44] GetInstalledVersion(): Quick Filters are missing
09:00:13.653: → [BaseUpdater:24] .ctor(): Installed version for DataUpdater: 0
09:00:13.654: → [AppUpdater:44] Initialize(): Previos version: 0.8.2245.37760
09:00:13.657: → [BaseUpdater:24] .ctor(): Installed version for AppUpdater: 0.8.2245.37760
09:00:13.658: → [BaseUpdater:24] .ctor(): Installed version for LocaleUpdater: 
09:00:13.735: → [VisualCppTool:43] Initialize(): Libraries load time: 0.3 ms
09:00:13.735: → [VisualCppTool:44] Initialize(): Current directory: C:\Users\jonas\Desktop
09:00:14.701: ⚠ [DataUpdater:44] GetInstalledVersion(): Quick Filters are missing
09:00:16.191: ⚠ [IniSettings:53] .ctor(): IniSettings exception: System.Exception: AcRootDirectory is required
	   at AcManager.Tools.Managers.AcRootDirectory.get_RequireValue()
	   at AcManager.Tools.Helpers.AcSettings.IniSettings..ctor(String name, Boolean reload, Boolean systemConfig)
09:00:29.322: → [Initial setup] AC root=“C:\Program Files (x86)\Steam\steamapps\common\assettocorsa”, Steam ID=“xxxxxxxxxxxxxxxxx”
09:00:29.344: → [Superintendent:72] RescanManagers(): Rescanning finished: 2 managers, 19.19 ms
09:00:29.369: → [AppUi:189] Run(): Main window…
09:00:29.372: → [BaseUpdater:24] .ctor(): Installed version for PatchUpdater: 
09:00:29.641: … [MainWindow:515] OnLoaded(): Main window is loaded and ready
09:00:29.643: … [ModernMenu:94] OnLoaded(): Can’t find link: 
09:00:29.862: → [WeatherManager] Async loading finished: 7 objects, 92 ms
09:00:29.885: ⚠ [DataProvider:90] Load(): Cannot load TagCountries.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass8_0`2.<Load>b__0()
09:00:29.885: ⚠ [DataProvider:90] Load(): Cannot load Countries.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass8_0`2.<Load>b__0()
09:00:29.885: ⚠ [DataProvider:90] Load(): Cannot load TagCountries.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass8_0`2.<Load>b__0()
09:00:29.886: ⚠ [DataProvider:90] Load(): Cannot load TagCountries.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass8_0`2.<Load>b__0()
09:00:29.894: ⚠ [DataProvider:77] Load(): Cannot load Years.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass7_0`1.<Load>b__0()
09:00:29.917: ⚠ [DataProvider:90] Load(): Cannot load BrandCountries.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass8_0`2.<Load>b__0()
09:00:29.985: ⚠ [DataProvider:102] Load(): Cannot load KunosContent.json: System.Exception: Can’t load data
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass9_0`1.<Load>b__0()
09:00:30.005: ⚠ [DataProvider:77] Load(): Cannot load KunosSkins.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass7_0`1.<Load>b__0()
09:00:30.017: … [TrackObject.Skins:315] DisplayActiveSkins(): No skins found
09:00:30.397: … [LapTimesSource:185] GetEntriesAsync(): Content Manager: 2.8 ms
09:00:30.523: → [TracksManager] Async loading finished: 21 objects, 124 ms
09:00:30.526: … [LapTimesSource:185] GetEntriesAsync(): AC New: 128.4 ms
09:00:30.528: … [LapTimesSource:185] GetEntriesAsync(): Sidekick: 2.1 ms
09:00:30.529: … [LapTimesSource:185] GetEntriesAsync(): Race Essentials: 0.3 ms
09:00:30.529: → [LapTimesManager:275] UpdateAsyncInner(): 136.89 ms
09:00:30.703: → [CarsManager] Async loading finished: 178 objects, 836 ms
09:00:32.423: ⚠ [DataProvider:77] Load(): Cannot load KunosDlcs.json: System.ArgumentNullException: Value cannot be null.
	Parameter name: value
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	   at AcManager.Tools.Data.DataProvider.<>c__DisplayClass7_0`1.<Load>b__0()
09:00:32.688: → [LapTimesManager:275] UpdateAsyncInner(): 0.01 ms
09:00:38.385: … [PatchUpdater:188] InstallVersion(): Installing: null
09:00:38.385: ⚠ [PatchUpdater:190] InstallVersion(): Already installed or null
09:00:46.947: ⚠ [I] Cannot get data: , The request was aborted: The request was canceled.
09:01:00.722: ⚠ [I] Cannot get data: , The request was aborted: The request was canceled.
09:01:00.723: • [PatchVersionInfo:564] GetPatchManifestAsync(): Can’t load the new version
09:01:00.725: … [PatchUpdater:244] CheckAndUpdateIfNeededInner(): Currently installed: nothing
09:01:00.725: → [PatchUpdater:282] CheckAndUpdateIfNeededInner(): Latest version: -1, installed: 
09:01:09.028: … [Superintendent:56] UnsavedChanges(): 

</details>

Is this a common problem or is this a problem with my windows/ content manager?

**Comment by flaw** [comment]
Did you by chance find a solution to this? I'm seeing similar behavior (although I don't see the specific error message you have): all game launches are taking forever since the requests for Custom Shader Patch track/car data seem to be hitting a 60 second timeout:
```
21:50:14.158: … [PatchBaseDataUpdater:467] TriggerAutoLoadAsync(): Loading entries list…
21:50:14.202: ⊕ [GameDialog:104] PrepareToFixSize()
21:51:14.162: ⚠ [ApiCacheThing:127] GetBytesAsyncInner(): System.Threading.Tasks.TaskCanceledException: A task was canceled.
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at AcManager.Tools.Helpers.Api.ApiCacheThing.<GetBytesAsyncInner>d__6.MoveNext()
21:51:14.163: … [PatchBaseDataUpdater:470] TriggerAutoLoadAsync(): Done: False

```

It's also similarly weird for me: CM can update itself and load the changelog, but it cannot for example check for CSP updates or install alternative versions of CSP. Trying to change CSP version results in a similar "check your internet connection" error.

@gro-ove any pointers you could share? I'm a bit at a loss what could cause selective network requests to fail, especially since both are aimed at github from what I can gather from the sources... perhaps some cache corruption issue?

**Comment by flaw** [comment]
Got it. In my case this was caused by a faulty network setup: I don't have proper IPv6 connectivity but I did have enough that DNS could resolve IPv6 addresses, and as it turns out `acstuff.ru` was resolved in IPv6 by CM/dotnet, causing the requests to timeout. 
The reason it was failing only for some domains was also that: not all domains resolve IPv6 addresses in which case this setup fell back to IPv4 which worked.

**Comment by yogithesymbian** [comment]
we have same issue 
```
⚠ [IniSettings:53] .ctor(): IniSettings exception: System.Exception: AcRootDirectory is required at AcManager.Tools.Managers.AcRootDirectory.get_RequireValue()
```

**Comment by yogithesymbian** [comment]
> we have same issue
> 
> ```
> ⚠ [IniSettings:53] .ctor(): IniSettings exception: System.Exception: AcRootDirectory is required at AcManager.Tools.Managers.AcRootDirectory.get_RequireValue()
> ```

Solved by reinstalling my bottle. I’m using Crossover on my MBP M1. 😄 However, now I can’t click 'OK'  I’ve purchased it. Not sure why this is happening. I’ve already emailed support and hope they reply to my issue soon.
