### ISSUE TITLE
Cannot install Custom Shaders Patch

### ISSUE THREAD

**Issue by dsieradzki** [gro-ove/actools#40]
Content Manager do not do anything when I'm try click "Install" on CSP

CM logs:
`09:27:30.348: … [PatchUpdater:207] InstallVersion(): Old version: none
09:27:30.351: … [PatchVersionInfo:485] InstallAsync(): Beginning patch installation, trying to install v0.1.60 (1048)
09:27:30.388: ⚠ [I] Checksum is missing or wrong
09:27:30.390: ⚠ [PatchUpdater:218] InstallVersion(): FirstFloor.ModernUI.Helpers.InformativeException: Can’t load the new version
	   at AcManager.Tools.Data.PatchVersionInfo.<InstallAsync>d__62.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at AcManager.Tools.Data.PatchUpdater.<InstallVersion>d__74.MoveNext()
	Commentary: Make sure Internet-connection works.
09:27:30.732: ⚠ [I] Checksum is missing or wrong
`

Tested on:
-  Fresh installation of Windows 10 Pro 21H1
- Windows 11 Preview

**Comment by NickGerm** [comment]
Im having the exact same problem on windows 10. My log is exactly the same except different times of execution
