### ISSUE TITLE
Packing a server doesn't seem to work on Windows 11

### ISSUE THREAD

**Issue by georgesvachulay** [gro-ove/actools#70]
When trying to pack a server on win 11 22H2, I get the following exception:
```
Oops!
Can't pack server:
Not allowed
```
After checking the logs I'm not much wiser:
```
11:05:41.330: • [PackServerDialog:219] PackCommand(): Can’t pack server:
	System.Exception: Not allowed
	   at AcTools.AcdFile.Acd.CompatibilityCheck(String filename)
	   at AcTools.AcdFile.Acd.Save(String filename)
	   at AcManager.Pages.Dialogs.PackServerDialog.<EnsurePacked>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at AcManager.Pages.Dialogs.PackServerDialog.ViewModel.<<get_PackCommand>b__38_0>d.MoveNext()
```
I don't get other errors and pressin Run on content manager for the server still works, it just can't seem to export.
Tried running as admin, picking a number of different folders as destination (same drive, other drive, user folder, system folder), changing the filename, changing the extension, ticking add executable, unticking add executable, none worked.

**Comment by Marocco2** [comment]
Do you have folder protection enabled?

**Comment by georgesvachulay** [comment]
> Do you have folder protection enabled?

If you mean the defender controlled folder access thing, nah that's never been enabled.

**Comment by georgesvachulay** [comment]
Oh yeah, one other thing is that saving anything else with CM works perfectly well  - e.g. config files, presets, cars, mods, tracks, basically everything except this.

**Comment by georgesvachulay** [comment]
it seems like this is related to car models. once i have removed all cars from the list of the server, it packed correctly. i'll need to debug further to tell what's causing it.
